### ISSUE TITLE
Login page UI

### ISSUE THREAD

**Issue by utsav-vaghani** [ultra-utsav/Book-Rentals#10]
create a login page for user.

Fields for login: 
Email         string   `json:"email"`
Password   string   `json:"password"`

**Comment by utsav-vaghani** [comment]
![Screenshot (61)](https://user-images.githubusercontent.com/40231426/101376549-bd004380-38d6-11eb-82b1-4fe0b80531ce.png)
As shown in Screenshot "Don't Have An Account? Forgot Your Password" should be in new line

**Comment by Tejas1510** [comment]
@ultra-utsav can i work on it

**Comment by CIPHERTron** [comment]
Hey @ultra-utsav can I work on this issue?
I can add some transition effects too!
