### ISSUE TITLE
Registration page ui

### ISSUE THREAD

**Issue by utsav-vaghani** [ultra-utsav/Book-Rentals#11]
create a registration page for user.

Fields for user registration:
Name          string `json:"name"`
Email           string `json:"email"`
Password    string `json:"password"`
Address      string `json:"address"`

**Comment by vishudhiman** [comment]
Can I submit my code?

**Comment by vishudhiman** [comment]
![main](https://user-images.githubusercontent.com/60461844/101280150-6a972800-37ed-11eb-87e8-40e44ba7a103.png)
![signin](https://user-images.githubusercontent.com/60461844/101280152-6cf98200-37ed-11eb-8b0e-c2b87f90037b.png)
![signup](https://user-images.githubusercontent.com/60461844/101280153-6e2aaf00-37ed-11eb-9848-3770b522e7ca.png)

**Comment by utsav-vaghani** [comment]
![Screenshot (62)](https://user-images.githubusercontent.com/40231426/101376742-fdf85800-38d6-11eb-87e2-bd97e781e1a7.png)
The registration form looks not good changes required.
