### ISSUE TITLE
create book form

### ISSUE THREAD

**Issue by utsav-vaghani** [ultra-utsav/Book-Rentals#14]

**Comment by Aaryan8751** [comment]
@ultra-utsav could you assign me this work and also please explain what fields you need in this form

**Comment by utsav-vaghani** [comment]
Title       string    `json:"title"`
	Author      string    `json:"author"`
	Description string    `json:"description"`
	Category    string    `json:"category"`
	OwnerID     string    `json:"owner_id"`
	Price       float     `json:"price"`
	Stock       int    `json:"stock"`
	NoOfPages   int     `json:"no_of_pages"`

name of fields are as given above in json

**Comment by Aaryan8751** [comment]
@ultra-utsav done and created a pull request.
